services:
  - type: web
    name: netline-chat
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gthread --threads 8 -w 1 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: CHAT_DB_PATH
        value: /var/data/chat.db
    disk:
      name: chat-data
      mountPath: /var/data
      sizeGB: 1
